server:
  port: 8085
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:  # 路由断言，
            - Path=/admin/**  #将admin/**开头的请求代理到lb://user-service这个uri上面，lb是负载均衡
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8085"
              - "https://questionnaire.neudeveloper.cn"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            max-age: 360000