#默认使用配置
spring:
  profiles:
      active: dev
  jpa:
   database: MYSQL

server:
  port: 8085

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.aim.questionnaire.entity
  mapperLocations: classpath:mapper/*.xml
  #开启MyBatis的二级缓存
  configuration:
    cache-enabled: true

# 分页配置
pagehelper:
  helperDalect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: conut=countSql

commonDS:
  # 配置初始化大小、最小、最大
  initialSize: 2
  minIdle: 2
  maxActive: 5
  #配置获取连接等待超时的时间
  maxWait: 60000
  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  #配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 60000

  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  #打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 5
  #配置监控统计拦截的filters，去掉后监控界面sql无法统计
  filters: stat,wall,slf4j
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  useGlobalDataSourceStat: true
  #durid监控配置
  loginUsername: star
  loginPassword: Star1234
  resetEnable: false
  rootPath: /druid/*

---

#开发配置
spring:
  profiles: dev
  datasource:
    #连接mysql5数据库
    url: jdbc:mysql://127.0.0.1:13306/questionnaire?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
    #连接mysql8数据库
#    url: jdbc:mysql://127.0.0.1:3306/questionnaire?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 111111
#    driver-class-name: com.mysql.jdbc.Driver

spring.mail:
  port:
  host:
  username:
  password:
  test-connection: false
  default-encoding: UTF-8
  properties:
    mail:
      debug: false
      smtp:
        timeout: 5000
        ssl:
          enable: true
        socketFactory:
          port:
          class:
        auth: true
        starttls:
          enable: true
          required: true
